### ISSUE TITLE
oozie spark2 action on kerberized cluster

### ISSUE THREAD

**Issue by jasonkoo** [fayson/cdhproject#2]
Hi,

最近在CDH集群中测试通过oozie提交spark action, 总是碰到问题。我希望通过oozie提交spark2的action，集群中启用了Kerberos，虽然按照提示配了principal和keytab，但一直出现认证失败的问题，不知道如何解决，期待能有一篇文章介绍这这个主题，谢谢！

**Comment by fayson** [comment]
你好，关于Oozie的一些使用，可以关注Fayson的公众号《Hadoop实操》，在必读中都可以找到

《如何使用Oozie API接口向非Kerberos环境的CDH集群提交Java作业》
《如何使用Oozie API接口向Kerberos环境的CDH集群提交Spark2作业》
《如何使用Oozie API接口向Kerberos环境的CDH集群提交Spark作业》
《如何使用Oozie API接口向Kerberos集群提交Java程序》

《如何使用Hue创建Spark2的Oozie工作流（补充）》
《如何使用Hue创建Spark1和Spark2的工作流》
《如何在Hue上创建一个完整Oozie工作流》
《如何在Hue中创建Ssh的Oozie工作流》
